debug: true
#Logging.level.org.springframework: debug
spring:
  # boot:
  # enableautoconfiguration: true
  # main:
  # web-application-type: SERVLET
  # # REACTIVE, SERVLET
  # banner-mode: "off"
  # profiles:
  #     default: "dev"
  messages:
    # 国际化资源文件路径 eg:"messages,config.i18n.messages"
    basename: messages/messages
    encoding: UTF-8
  servlet:
    multipart:
      enabled: true
      max-request-size: 10MB
      max-file-size: 10MB
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springboot?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: 12345678
  devtools:
    restart:
      exclude: logs/**
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  security:
    user:
      password: Test123456_
server:
  port: 9090
  tomcat:
    uri-encoding: utf-8
# 监控配置 访问 http://localhost:9999/actuator/
management:
  server:
    port: 9999
  endpoints:
    web:
      exposure:
        include: "*"
#在application.yml引入log4j2.yml
logging:
  config: classpath:log4j2.yml
application:
  name: cruncher
applicationID: ShopBackService
serviceID: ShopBackService
i18n:
  defaultLang: zh
  # jp: i18n/jp_msg.yml
  # zh: i18n/zh_msg.yml
  # messages:
  #   # jp: classpath:i18n/jp_msg.yml
  #   # zh: classpath:i18n/zh_msg.yml
  #   jp:
  #     hello: hello jp
  #   zh:
  #     hello: hello zh

jwt:
  private.key: classpath:keys/app.key

  public.key: classpath:keys/app.pub
terminalType:
  CostumerMobile:
    - User
  ShopWeb:
    - Staff
allowedOrigin:
  - http://localhost:8080
  - https://localhost:8080


cloud:
  aws:
    credentials:
      accessKey: your-access-key
      secretKey: your-secret-key
    stack:
      auto: false
    region:
      auto: false
      static: ap-northeast-1  # tokyo
    s3:
      bucket: your-bucket-name